###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
  memcached:
    image: "memcached:alpine"

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "49001:8025"

  redis:
    image: "redis:alpine"

  mariadb:
    image: "mariadb:11.0"
    working_dir: /application
    volumes:
      - "invoice-mariabd:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=invoiceme
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    ports:
      - "49003:3306"

  webserver:
    image: "nginx:alpine"
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "49000:80"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini"
    user: "${UID:-1000}:${GID:-1000}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    invoice-mariabd:
        driver: local
